### PR TITLE
Added GrenadeRestriction mod

### PR DESCRIPTION
**Pull request by notpeelz**
I made a script some time ago and just migrated it to GoonMod's mod system, so I thought I might as well propose this feature, as it would make a nice addition to this project.

### CODE REVIEW

**Comment by JamesWilko** [comment]
Sorry it's taken ages to get back to this, but if it's ok with you, I'll include this in the next proper update to add and fix things.

**Comment by LouisTakePILLz** [comment]
@JamesWilko Surely, just make sure to merge the pull request as opposed to manually pushing the content upstream, perhaps to another branch?

I believe a separate branch should be used to develop the mod, and the `master` for the latest stable release, so changes made while in-dev. do not affect the updating mechanism.

**Comment by JamesWilko** [comment]
I've got two repo's for the mod, this one, and a private development repo which contains all the latest changes. When putting out an update, I run the mod files through a processor which removes all the debug code and makes sure to only include the files which should be made public with the latest download. Since I've got a lot of debug commands and test code, lots of which I'd rather not make public since it can be used very easily for cheating.

**Comment by LouisTakePILLz** [comment]
@JamesWilko Any idea how your current setup could be adapted in order to make public contributions easier to handle? Perhaps the debug scripts could be refactored for easy exclusion using `.gitignore`?

**Comment by LouisTakePILLz** [comment]
@JamesWilko Any update regarding my contribution?

**Comment by JamesWilko** [comment]
I've been busy working on the custom lua hook and making sure that it's all working correctly, and fixing bugs that pop up with it. Once it's ready to go, I'll sort out this.

**Comment by JamesWilko** [comment]
Closing all pull requests due to large changes introduced in BLT release.

**Pull request closed without merging**
